pool:
  name: 'Hosted VS2017'

trigger:
  branches:
    include:
      - master
      - beta
      - release/beta/*
      - stable
      - release/stable/*

pr: 
  branches:
    include:
      - master
      - beta
      - release/beta/*
      - stable
      - release/stable/*

steps:
  - checkout: self
    clean: true

  - powershell: './build/build.ps1 -Script build/build.cake'

  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
        **\*test*.dll
        !**\obj\**
      vstestLocationMethod: version
      vsTestVersion: latest
      testSelector: testAssemblies

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(Build.SourcesDirectory)/build
      Contents: '*.nupkg'
      TargetFolder: $(Build.ArtifactStagingDirectory)/vs2017

  - task: PowerShell@2
    displayName: Authenticode Sign Packages
    inputs:
      filePath: build/Sign-Package.ps1
    env:
      SignClientUser: $(SignClientUser)
      SignClientSecret: $(SignClientSecret)
      SignPackageName: "Uno.PackageDiff"
      SignPackageDescription: "Uno.PackageDiff"
      ArtifactDirectory: $(build.artifactstagingdirectory)
    condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: $(Build.DefinitionName)